//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputInfo
    {
        public int Id { get; set; }
        public int IdOutput { get; set; }
        public int IdGood { get; set; }
        public int NumberOutput { get; set; }
        public float PricesOutput { get; set; }
        public Nullable<float> Tax { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Output Output { get; set; }
    }
}
