//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ListInput
    {
        public string Maphieunhap { get; set; }
        public System.DateTime Ngaynhap { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public string Ngay { get; set; }
        public string Mahang { get; set; }
        public string Tenhang { get; set; }
        public int Soluongnhap { get; set; }
        public float Dongianhap { get; set; }
        public Nullable<float> Thue { get; set; }
        public Nullable<float> Thanhtien { get; set; }
    }
}
