//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeWebByASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertise
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string url { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Link { get; set; }
        public Nullable<int> Targets { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Orders { get; set; }
        public Nullable<int> Statuss { get; set; }
    }
}
