//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangApp.Model
{
    using QuanLyCuaHangApp.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class CustomerBU : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerBU()
        {
            this.Outputs = new HashSet<Output>();
        }

        private int _id;
        public int Id { get { return _id; } set { _id = value; OnPropertyChanged(); } }
        private string _Customer1;
        public string Customer1 { get { return _Customer1; } set { _Customer1 = value; OnPropertyChanged(); } }
        private string _NameCus;
        public string NameCus { get { return _NameCus; } set { _NameCus = value; OnPropertyChanged(); } }
        private string _Adress;
        public string Adress { get { return _Adress; } set { _Adress = value; OnPropertyChanged(); } }
        private string _Phone;
        public string Phone { get { return _Phone; } set { _Phone = value; OnPropertyChanged(); } }
        private string _Email;
        public string Email { get { return _Email; } set { _Email = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Output> Outputs { get; set; }
    }
}
