//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace QuanLyCuaHangApp.Model
{
    using QuanLyCuaHangApp.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SuplierBU : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuplierBU()
        {
            this.Inputs = new HashSet<Input>();
        }

        private int _id;
        public int Id { get { return _id; } set { _id = value;  OnPropertyChanged(); } }
        private string _Suplier1;
        public string Suplier1 { get { return _Suplier1; } set { _Suplier1 = value; OnPropertyChanged(); } }
        private string _NameSup;
        public string NameSup { get { return _NameSup; } set { _NameSup = value; OnPropertyChanged(); } }
        private string _AddressSup;
        public string AddressSup { get { return _AddressSup; } set { _AddressSup = value; OnPropertyChanged(); } }
        private string _Phone;
        public string Phone { get { return _Phone; } set { _Phone = value; OnPropertyChanged(); } }
        private string _Email;
        public string Email { get { return _Email; } set { _Email = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input> Inputs { get; set; }
    }
}
