//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Input
    {
        public string Tên_nhân_viên { get; set; }
        public string Nhà_cung_cấp { get; set; }
        public string Địa_chỉ_NCC { get; set; }
        public string Điện_Thoại { get; set; }
        public string Email { get; set; }
        public string Mã_phiếu_nhập { get; set; }
        public string Ngày_nhập { get; set; }
        public string Tên_hàng { get; set; }
        public string Mô_tả { get; set; }
        public string Đơn_vị_tính { get; set; }
        public Nullable<float> Thuế_nhập { get; set; }
        public Nullable<float> Tiền_thuế { get; set; }
        public Nullable<float> Tổng_giá_trị { get; set; }
    }
}
