//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ListOutput
    {
        public string Mã_phiếu_xuất { get; set; }
        public string Ngày { get; set; }
        public Nullable<int> Tháng { get; set; }
        public Nullable<int> Năm { get; set; }
        public string Tên_hàng { get; set; }
        public int Số_lượng_xuất { get; set; }
        public float Giá_xuất { get; set; }
        public Nullable<float> Thuế { get; set; }
        public Nullable<float> Thành_tiền { get; set; }
    }
}
